// Code generated by "stringer -type DeliveryReliability"; DO NOT EDIT.

package broker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeliveryReliability_AtMostOnce-0]
	_ = x[DeliveryReliability_AtLeastOnce-1]
}

const _DeliveryReliability_name = "DeliveryReliability_AtMostOnceDeliveryReliability_AtLeastOnce"

var _DeliveryReliability_index = [...]uint8{0, 30, 61}

func (i DeliveryReliability) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeliveryReliability_index)-1 {
		return "DeliveryReliability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeliveryReliability_name[_DeliveryReliability_index[idx]:_DeliveryReliability_index[idx+1]]
}
