// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/dsync'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/option"
	"git.golaxy.org/framework/plugins/dsync"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/dsync/dsync"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrNotAcquired": reflect.ValueOf(&dsync.ErrNotAcquired).Elem(),
		"Name":           reflect.ValueOf(&dsync.Name).Elem(),
		"Using":          reflect.ValueOf(&dsync.Using).Elem(),
		"With":           reflect.ValueOf(&dsync.With).Elem(),

		// type definitions
		"DistMutexOptions":   reflect.ValueOf((*dsync.DistMutexOptions)(nil)),
		"IDistMutex":         reflect.ValueOf((*dsync.IDistMutex)(nil)),
		"IDistMutexSettings": reflect.ValueOf((*dsync.IDistMutexSettings)(nil)),
		"IDistSync":          reflect.ValueOf((*dsync.IDistSync)(nil)),

		// interface wrapper definitions
		"_IDistMutex":         reflect.ValueOf((*_git_golaxy_org_framework_plugins_dsync_IDistMutex)(nil)),
		"_IDistMutexSettings": reflect.ValueOf((*_git_golaxy_org_framework_plugins_dsync_IDistMutexSettings)(nil)),
		"_IDistSync":          reflect.ValueOf((*_git_golaxy_org_framework_plugins_dsync_IDistSync)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_dsync_IDistMutex is an interface wrapper for IDistMutex type
type _git_golaxy_org_framework_plugins_dsync_IDistMutex struct {
	IValue  interface{}
	WExtend func(ctx context.Context) error
	WLock   func(ctx context.Context) error
	WName   func() string
	WUnlock func(ctx context.Context) error
	WUntil  func() time.Time
	WValid  func(ctx context.Context) (bool, error)
	WValue  func() string
}

func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Extend(ctx context.Context) error {
	return W.WExtend(ctx)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Lock(ctx context.Context) error {
	return W.WLock(ctx)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Name() string {
	return W.WName()
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Unlock(ctx context.Context) error {
	return W.WUnlock(ctx)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Until() time.Time {
	return W.WUntil()
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Valid(ctx context.Context) (bool, error) {
	return W.WValid(ctx)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistMutex) Value() string {
	return W.WValue()
}

// _git_golaxy_org_framework_plugins_dsync_IDistMutexSettings is an interface wrapper for IDistMutexSettings type
type _git_golaxy_org_framework_plugins_dsync_IDistMutexSettings struct {
	IValue interface{}
	WWith  func(settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex
}

func (W _git_golaxy_org_framework_plugins_dsync_IDistMutexSettings) With(settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex {
	return W.WWith(settings...)
}

// _git_golaxy_org_framework_plugins_dsync_IDistSync is an interface wrapper for IDistSync type
type _git_golaxy_org_framework_plugins_dsync_IDistSync struct {
	IValue        interface{}
	WGetSeparator func() string
	WNewMutex     func(name string, settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex
	WNewMutexf    func(format string, args ...any) dsync.IDistMutexSettings
	WNewMutexp    func(elems ...string) dsync.IDistMutexSettings
}

func (W _git_golaxy_org_framework_plugins_dsync_IDistSync) GetSeparator() string {
	return W.WGetSeparator()
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistSync) NewMutex(name string, settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex {
	return W.WNewMutex(name, settings...)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistSync) NewMutexf(format string, args ...any) dsync.IDistMutexSettings {
	return W.WNewMutexf(format, args...)
}
func (W _git_golaxy_org_framework_plugins_dsync_IDistSync) NewMutexp(elems ...string) dsync.IDistMutexSettings {
	return W.WNewMutexp(elems...)
}
