// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/dentq'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/uid"
	"git.golaxy.org/framework/plugins/dentq"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/dentq/dentq"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&dentq.Install).Elem(),
		"Name":      reflect.ValueOf(&dentq.Name).Elem(),
		"Uninstall": reflect.ValueOf(&dentq.Uninstall).Elem(),
		"Using":     reflect.ValueOf(&dentq.Using).Elem(),
		"With":      reflect.ValueOf(&dentq.With).Elem(),

		// type definitions
		"DistEntity":               reflect.ValueOf((*dentq.DistEntity)(nil)),
		"DistEntityQuerierOptions": reflect.ValueOf((*dentq.DistEntityQuerierOptions)(nil)),
		"IDistEntityQuerier":       reflect.ValueOf((*dentq.IDistEntityQuerier)(nil)),
		"Node":                     reflect.ValueOf((*dentq.Node)(nil)),

		// interface wrapper definitions
		"_IDistEntityQuerier": reflect.ValueOf((*_git_golaxy_org_framework_plugins_dentq_IDistEntityQuerier)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_dentq_IDistEntityQuerier is an interface wrapper for IDistEntityQuerier type
type _git_golaxy_org_framework_plugins_dentq_IDistEntityQuerier struct {
	IValue         interface{}
	WGetDistEntity func(id uid.Id) (*dentq.DistEntity, bool)
}

func (W _git_golaxy_org_framework_plugins_dentq_IDistEntityQuerier) GetDistEntity(id uid.Id) (*dentq.DistEntity, bool) {
	return W.WGetDistEntity(id)
}
