// Code generated by 'yaegi extract git.golaxy.org/core/utils'. DO NOT EDIT.

package fwlib

import (
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/utils"] = map[string]reflect.Value{}
}
