// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/db/sqldb'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/db/sqldb"
	"gorm.io/gorm"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/db/sqldb/sqldb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&sqldb.Install).Elem(),
		"Name":      reflect.ValueOf(&sqldb.Name).Elem(),
		"Uninstall": reflect.ValueOf(&sqldb.Uninstall).Elem(),
		"Using":     reflect.ValueOf(&sqldb.Using).Elem(),
		"With":      reflect.ValueOf(&sqldb.With).Elem(),

		// type definitions
		"ISQLDB":       reflect.ValueOf((*sqldb.ISQLDB)(nil)),
		"SQLDBOptions": reflect.ValueOf((*sqldb.SQLDBOptions)(nil)),

		// interface wrapper definitions
		"_ISQLDB": reflect.ValueOf((*_git_golaxy_org_framework_plugins_db_sqldb_ISQLDB)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_db_sqldb_ISQLDB is an interface wrapper for ISQLDB type
type _git_golaxy_org_framework_plugins_db_sqldb_ISQLDB struct {
	IValue interface{}
	WSQLDB func(tag string) *gorm.DB
}

func (W _git_golaxy_org_framework_plugins_db_sqldb_ISQLDB) SQLDB(tag string) *gorm.DB {
	return W.WSQLDB(tag)
}
