// Code generated by 'yaegi extract git.golaxy.org/core/utils/exception'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/exception"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/exception/exception"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrArgs":         reflect.ValueOf(&exception.ErrArgs).Elem(),
		"ErrCore":         reflect.ValueOf(&exception.ErrCore).Elem(),
		"ErrPanicked":     reflect.ValueOf(&exception.ErrPanicked).Elem(),
		"PrintStackTrace": reflect.ValueOf(exception.PrintStackTrace),
	}
}
