// Code generated by 'yaegi extract git.golaxy.org/core/utils/generic'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/generic"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/generic/generic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FuncError": reflect.ValueOf(generic.FuncError),

		// type definitions
		"Action0":         reflect.ValueOf((*generic.Action0)(nil)),
		"DelegateAction0": reflect.ValueOf((*generic.DelegateAction0)(nil)),
	}
}
