// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/db/mongodb'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/db/mongodb"
	"go.mongodb.org/mongo-driver/mongo"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/db/mongodb/mongodb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&mongodb.Install).Elem(),
		"Name":      reflect.ValueOf(&mongodb.Name).Elem(),
		"Uninstall": reflect.ValueOf(&mongodb.Uninstall).Elem(),
		"Using":     reflect.ValueOf(&mongodb.Using).Elem(),
		"With":      reflect.ValueOf(&mongodb.With).Elem(),

		// type definitions
		"IMongoDB":       reflect.ValueOf((*mongodb.IMongoDB)(nil)),
		"MongoDBOptions": reflect.ValueOf((*mongodb.MongoDBOptions)(nil)),

		// interface wrapper definitions
		"_IMongoDB": reflect.ValueOf((*_git_golaxy_org_framework_plugins_db_mongodb_IMongoDB)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_db_mongodb_IMongoDB is an interface wrapper for IMongoDB type
type _git_golaxy_org_framework_plugins_db_mongodb_IMongoDB struct {
	IValue   interface{}
	WMongoDB func(tag string) *mongo.Client
}

func (W _git_golaxy_org_framework_plugins_db_mongodb_IMongoDB) MongoDB(tag string) *mongo.Client {
	return W.WMongoDB(tag)
}
