// Code generated by 'yaegi extract git.golaxy.org/core/utils/reinterpret'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/iface"
	"git.golaxy.org/core/utils/reinterpret"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/reinterpret/reinterpret"] = map[string]reflect.Value{
		// type definitions
		"InstanceProvider": reflect.ValueOf((*reinterpret.InstanceProvider)(nil)),

		// interface wrapper definitions
		"_InstanceProvider": reflect.ValueOf((*_git_golaxy_org_core_utils_reinterpret_InstanceProvider)(nil)),
	}
}

// _git_golaxy_org_core_utils_reinterpret_InstanceProvider is an interface wrapper for InstanceProvider type
type _git_golaxy_org_core_utils_reinterpret_InstanceProvider struct {
	IValue                interface{}
	WGetInstanceFaceCache func() iface.Cache
}

func (W _git_golaxy_org_core_utils_reinterpret_InstanceProvider) GetInstanceFaceCache() iface.Cache {
	return W.WGetInstanceFaceCache()
}
