// Code generated by 'yaegi extract git.golaxy.org/core/define'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/define"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/define/define"] = map[string]reflect.Value{
		// type definitions
		"ComponentDefinition": reflect.ValueOf((*define.ComponentDefinition)(nil)),
	}
}
