// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/rpcstack'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/generic"
	"git.golaxy.org/framework/net/gap/variant"
	"git.golaxy.org/framework/plugins/rpcstack"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/rpcstack/rpcstack"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"EmptyCallChain": reflect.ValueOf(&rpcstack.EmptyCallChain).Elem(),
		"Install":        reflect.ValueOf(&rpcstack.Install).Elem(),
		"Name":           reflect.ValueOf(&rpcstack.Name).Elem(),
		"Uninstall":      reflect.ValueOf(&rpcstack.Uninstall).Elem(),
		"UnsafeRPCStack": reflect.ValueOf(rpcstack.UnsafeRPCStack),
		"Using":          reflect.ValueOf(&rpcstack.Using).Elem(),

		// type definitions
		"Call":      reflect.ValueOf((*rpcstack.Call)(nil)),
		"CallChain": reflect.ValueOf((*rpcstack.CallChain)(nil)),
		"IRPCStack": reflect.ValueOf((*rpcstack.IRPCStack)(nil)),

		// interface wrapper definitions
		"_IRPCStack": reflect.ValueOf((*_git_golaxy_org_framework_plugins_rpcstack_IRPCStack)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_rpcstack_IRPCStack is an interface wrapper for IRPCStack type
type _git_golaxy_org_framework_plugins_rpcstack_IRPCStack struct {
	IValue     interface{}
	WCallChain func() variant.CallChain
	WVariables func() *generic.UnorderedSliceMap[string, any]
}

func (W _git_golaxy_org_framework_plugins_rpcstack_IRPCStack) CallChain() variant.CallChain {
	return W.WCallChain()
}
func (W _git_golaxy_org_framework_plugins_rpcstack_IRPCStack) Variables() *generic.UnorderedSliceMap[string, any] {
	return W.WVariables()
}
