// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/discovery/redis_discovery'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/discovery/redis_discovery"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/discovery/redis_discovery/redis_discovery"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":     reflect.ValueOf(&redis_discovery.Install).Elem(),
		"NewRegistry": reflect.ValueOf(redis_discovery.NewRegistry),
		"Uninstall":   reflect.ValueOf(&redis_discovery.Uninstall).Elem(),
		"With":        reflect.ValueOf(&redis_discovery.With).Elem(),

		// type definitions
		"RegistryOptions": reflect.ValueOf((*redis_discovery.RegistryOptions)(nil)),
	}
}
