// Code generated by 'yaegi extract git.golaxy.org/core/utils/iface'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/iface"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/iface/iface"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NilCache": reflect.ValueOf(&iface.NilCache).Elem(),

		// type definitions
		"Cache": reflect.ValueOf((*iface.Cache)(nil)),
	}
}
