// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/dsync/etcd_dsync'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/dsync/etcd_dsync"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/dsync/etcd_dsync/etcd_dsync"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&etcd_dsync.Install).Elem(),
		"Uninstall": reflect.ValueOf(&etcd_dsync.Uninstall).Elem(),
		"With":      reflect.ValueOf(&etcd_dsync.With).Elem(),

		// type definitions
		"DSyncOptions": reflect.ValueOf((*etcd_dsync.DSyncOptions)(nil)),
	}
}
