// Code generated by 'yaegi extract git.golaxy.org/core/utils/option'. DO NOT EDIT.

package fwlib

import (
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/option/option"] = map[string]reflect.Value{}
}
