// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/db'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/db"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MongoDB":    reflect.ValueOf(constant.MakeFromLiteral("\"mongodb\"", token.STRING, 0)),
		"MySQL":      reflect.ValueOf(constant.MakeFromLiteral("\"mysql\"", token.STRING, 0)),
		"PostgreSQL": reflect.ValueOf(constant.MakeFromLiteral("\"postgresql\"", token.STRING, 0)),
		"Redis":      reflect.ValueOf(constant.MakeFromLiteral("\"redis\"", token.STRING, 0)),
		"SQLServer":  reflect.ValueOf(constant.MakeFromLiteral("\"sqlserver\"", token.STRING, 0)),
		"SQLite":     reflect.ValueOf(constant.MakeFromLiteral("\"sqlite\"", token.STRING, 0)),

		// type definitions
		"DBInfo": reflect.ValueOf((*db.DBInfo)(nil)),
	}
}
