// Code generated by 'yaegi extract git.golaxy.org/core/utils/types'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/types"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bytes2String":     reflect.ValueOf(types.Bytes2String),
		"FullName":         reflect.ValueOf(types.FullName),
		"FullNameRT":       reflect.ValueOf(types.FullNameRT),
		"Name":             reflect.ValueOf(types.Name),
		"NameRT":           reflect.ValueOf(types.NameRT),
		"Panic2Err":        reflect.ValueOf(types.Panic2Err),
		"String2Bytes":     reflect.ValueOf(types.String2Bytes),
		"WriteAnyFullName": reflect.ValueOf(types.WriteAnyFullName),
		"WriteFullNameRT":  reflect.ValueOf(types.WriteFullNameRT),
	}
}
