// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/conf'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/conf"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/conf/conf"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&conf.Install).Elem(),
		"Name":      reflect.ValueOf(&conf.Name).Elem(),
		"Uninstall": reflect.ValueOf(&conf.Uninstall).Elem(),
		"Using":     reflect.ValueOf(&conf.Using).Elem(),
		"With":      reflect.ValueOf(&conf.With).Elem(),

		// type definitions
		"ConfigOptions": reflect.ValueOf((*conf.ConfigOptions)(nil)),
		"IConfig":       reflect.ValueOf((*conf.IConfig)(nil)),
		"IVisitConf":    reflect.ValueOf((*conf.IVisitConf)(nil)),

		// interface wrapper definitions
		"_IConfig":    reflect.ValueOf((*_git_golaxy_org_framework_plugins_conf_IConfig)(nil)),
		"_IVisitConf": reflect.ValueOf((*_git_golaxy_org_framework_plugins_conf_IVisitConf)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_conf_IConfig is an interface wrapper for IConfig type
type _git_golaxy_org_framework_plugins_conf_IConfig struct {
	IValue                            interface{}
	WGet                              func(key string) any
	WGetAllKeys                       func() []string
	WGetAllSettings                   func() map[string]any
	WGetBool                          func(key string) bool
	WGetBoolOrDefault                 func(key string, def bool) bool
	WGetDuration                      func(key string) time.Duration
	WGetDurationOrDefault             func(key string, def time.Duration) time.Duration
	WGetFloat64                       func(key string) float64
	WGetFloat64OrDefault              func(key string, def float64) float64
	WGetInt                           func(key string) int
	WGetInt32                         func(key string) int32
	WGetInt32OrDefault                func(key string, def int32) int32
	WGetInt64                         func(key string) int64
	WGetInt64OrDefault                func(key string, def int64) int64
	WGetIntOrDefault                  func(key string, def int) int
	WGetIntSlice                      func(key string) []int
	WGetIntSliceOrDefault             func(key string, def []int) []int
	WGetSizeInBytes                   func(key string) uint
	WGetString                        func(key string) string
	WGetStringMap                     func(key string) map[string]any
	WGetStringMapOrDefault            func(key string, def map[string]any) map[string]any
	WGetStringMapString               func(key string) map[string]string
	WGetStringMapStringOrDefault      func(key string, def map[string]string) map[string]string
	WGetStringMapStringSlice          func(key string) map[string][]string
	WGetStringMapStringSliceOrDefault func(key string, def map[string][]string) map[string][]string
	WGetStringOrDefault               func(key string, def string) string
	WGetStringSlice                   func(key string) []string
	WGetStringSliceOrDefault          func(key string, def []string) []string
	WGetTime                          func(key string) time.Time
	WGetTimeOrDefault                 func(key string, def time.Time) time.Time
	WGetUint                          func(key string) uint
	WGetUint16                        func(key string) uint16
	WGetUint16OrDefault               func(key string, def uint16) uint16
	WGetUint32                        func(key string) uint32
	WGetUint32OrDefault               func(key string, def uint32) uint32
	WGetUint64                        func(key string) uint64
	WGetUint64OrDefault               func(key string, def uint64) uint64
	WGetUintOrDefault                 func(key string, def uint) uint
	WSub                              func(key string) conf.IVisitConf
	WWhole                            func() conf.IVisitConf
}

func (W _git_golaxy_org_framework_plugins_conf_IConfig) Get(key string) any {
	return W.WGet(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetAllKeys() []string {
	return W.WGetAllKeys()
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetAllSettings() map[string]any {
	return W.WGetAllSettings()
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetBool(key string) bool {
	return W.WGetBool(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetBoolOrDefault(key string, def bool) bool {
	return W.WGetBoolOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetDuration(key string) time.Duration {
	return W.WGetDuration(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetDurationOrDefault(key string, def time.Duration) time.Duration {
	return W.WGetDurationOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetFloat64(key string) float64 {
	return W.WGetFloat64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetFloat64OrDefault(key string, def float64) float64 {
	return W.WGetFloat64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetInt(key string) int {
	return W.WGetInt(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetInt32(key string) int32 {
	return W.WGetInt32(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetInt32OrDefault(key string, def int32) int32 {
	return W.WGetInt32OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetInt64(key string) int64 {
	return W.WGetInt64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetInt64OrDefault(key string, def int64) int64 {
	return W.WGetInt64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetIntOrDefault(key string, def int) int {
	return W.WGetIntOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetIntSlice(key string) []int {
	return W.WGetIntSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetIntSliceOrDefault(key string, def []int) []int {
	return W.WGetIntSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetSizeInBytes(key string) uint {
	return W.WGetSizeInBytes(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetString(key string) string {
	return W.WGetString(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMap(key string) map[string]any {
	return W.WGetStringMap(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMapOrDefault(key string, def map[string]any) map[string]any {
	return W.WGetStringMapOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMapString(key string) map[string]string {
	return W.WGetStringMapString(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMapStringOrDefault(key string, def map[string]string) map[string]string {
	return W.WGetStringMapStringOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMapStringSlice(key string) map[string][]string {
	return W.WGetStringMapStringSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringMapStringSliceOrDefault(key string, def map[string][]string) map[string][]string {
	return W.WGetStringMapStringSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringOrDefault(key string, def string) string {
	return W.WGetStringOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringSlice(key string) []string {
	return W.WGetStringSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetStringSliceOrDefault(key string, def []string) []string {
	return W.WGetStringSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetTime(key string) time.Time {
	return W.WGetTime(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetTimeOrDefault(key string, def time.Time) time.Time {
	return W.WGetTimeOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint(key string) uint {
	return W.WGetUint(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint16(key string) uint16 {
	return W.WGetUint16(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint16OrDefault(key string, def uint16) uint16 {
	return W.WGetUint16OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint32(key string) uint32 {
	return W.WGetUint32(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint32OrDefault(key string, def uint32) uint32 {
	return W.WGetUint32OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint64(key string) uint64 {
	return W.WGetUint64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUint64OrDefault(key string, def uint64) uint64 {
	return W.WGetUint64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) GetUintOrDefault(key string, def uint) uint {
	return W.WGetUintOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) Sub(key string) conf.IVisitConf {
	return W.WSub(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IConfig) Whole() conf.IVisitConf {
	return W.WWhole()
}

// _git_golaxy_org_framework_plugins_conf_IVisitConf is an interface wrapper for IVisitConf type
type _git_golaxy_org_framework_plugins_conf_IVisitConf struct {
	IValue                            interface{}
	WGet                              func(key string) any
	WGetAllKeys                       func() []string
	WGetAllSettings                   func() map[string]any
	WGetBool                          func(key string) bool
	WGetBoolOrDefault                 func(key string, def bool) bool
	WGetDuration                      func(key string) time.Duration
	WGetDurationOrDefault             func(key string, def time.Duration) time.Duration
	WGetFloat64                       func(key string) float64
	WGetFloat64OrDefault              func(key string, def float64) float64
	WGetInt                           func(key string) int
	WGetInt32                         func(key string) int32
	WGetInt32OrDefault                func(key string, def int32) int32
	WGetInt64                         func(key string) int64
	WGetInt64OrDefault                func(key string, def int64) int64
	WGetIntOrDefault                  func(key string, def int) int
	WGetIntSlice                      func(key string) []int
	WGetIntSliceOrDefault             func(key string, def []int) []int
	WGetSizeInBytes                   func(key string) uint
	WGetString                        func(key string) string
	WGetStringMap                     func(key string) map[string]any
	WGetStringMapOrDefault            func(key string, def map[string]any) map[string]any
	WGetStringMapString               func(key string) map[string]string
	WGetStringMapStringOrDefault      func(key string, def map[string]string) map[string]string
	WGetStringMapStringSlice          func(key string) map[string][]string
	WGetStringMapStringSliceOrDefault func(key string, def map[string][]string) map[string][]string
	WGetStringOrDefault               func(key string, def string) string
	WGetStringSlice                   func(key string) []string
	WGetStringSliceOrDefault          func(key string, def []string) []string
	WGetTime                          func(key string) time.Time
	WGetTimeOrDefault                 func(key string, def time.Time) time.Time
	WGetUint                          func(key string) uint
	WGetUint16                        func(key string) uint16
	WGetUint16OrDefault               func(key string, def uint16) uint16
	WGetUint32                        func(key string) uint32
	WGetUint32OrDefault               func(key string, def uint32) uint32
	WGetUint64                        func(key string) uint64
	WGetUint64OrDefault               func(key string, def uint64) uint64
	WGetUintOrDefault                 func(key string, def uint) uint
	WSub                              func(key string) conf.IVisitConf
}

func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) Get(key string) any {
	return W.WGet(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetAllKeys() []string {
	return W.WGetAllKeys()
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetAllSettings() map[string]any {
	return W.WGetAllSettings()
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetBool(key string) bool {
	return W.WGetBool(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetBoolOrDefault(key string, def bool) bool {
	return W.WGetBoolOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetDuration(key string) time.Duration {
	return W.WGetDuration(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetDurationOrDefault(key string, def time.Duration) time.Duration {
	return W.WGetDurationOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetFloat64(key string) float64 {
	return W.WGetFloat64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetFloat64OrDefault(key string, def float64) float64 {
	return W.WGetFloat64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetInt(key string) int {
	return W.WGetInt(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetInt32(key string) int32 {
	return W.WGetInt32(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetInt32OrDefault(key string, def int32) int32 {
	return W.WGetInt32OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetInt64(key string) int64 {
	return W.WGetInt64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetInt64OrDefault(key string, def int64) int64 {
	return W.WGetInt64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetIntOrDefault(key string, def int) int {
	return W.WGetIntOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetIntSlice(key string) []int {
	return W.WGetIntSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetIntSliceOrDefault(key string, def []int) []int {
	return W.WGetIntSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetSizeInBytes(key string) uint {
	return W.WGetSizeInBytes(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetString(key string) string {
	return W.WGetString(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMap(key string) map[string]any {
	return W.WGetStringMap(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMapOrDefault(key string, def map[string]any) map[string]any {
	return W.WGetStringMapOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMapString(key string) map[string]string {
	return W.WGetStringMapString(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMapStringOrDefault(key string, def map[string]string) map[string]string {
	return W.WGetStringMapStringOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMapStringSlice(key string) map[string][]string {
	return W.WGetStringMapStringSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringMapStringSliceOrDefault(key string, def map[string][]string) map[string][]string {
	return W.WGetStringMapStringSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringOrDefault(key string, def string) string {
	return W.WGetStringOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringSlice(key string) []string {
	return W.WGetStringSlice(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetStringSliceOrDefault(key string, def []string) []string {
	return W.WGetStringSliceOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetTime(key string) time.Time {
	return W.WGetTime(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetTimeOrDefault(key string, def time.Time) time.Time {
	return W.WGetTimeOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint(key string) uint {
	return W.WGetUint(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint16(key string) uint16 {
	return W.WGetUint16(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint16OrDefault(key string, def uint16) uint16 {
	return W.WGetUint16OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint32(key string) uint32 {
	return W.WGetUint32(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint32OrDefault(key string, def uint32) uint32 {
	return W.WGetUint32OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint64(key string) uint64 {
	return W.WGetUint64(key)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUint64OrDefault(key string, def uint64) uint64 {
	return W.WGetUint64OrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) GetUintOrDefault(key string, def uint) uint {
	return W.WGetUintOrDefault(key, def)
}
func (W _git_golaxy_org_framework_plugins_conf_IVisitConf) Sub(key string) conf.IVisitConf {
	return W.WSub(key)
}
