// Code generated by 'yaegi extract git.golaxy.org/core/ec'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/event"
	"git.golaxy.org/core/utils/generic"
	"git.golaxy.org/core/utils/iface"
	"git.golaxy.org/core/utils/uid"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/core/ec/ec"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindEventComponentDestroySelf":               reflect.ValueOf(ec.BindEventComponentDestroySelf),
		"BindEventComponentMgrAddComponents":          reflect.ValueOf(ec.BindEventComponentMgrAddComponents),
		"BindEventComponentMgrFirstAccessComponent":   reflect.ValueOf(ec.BindEventComponentMgrFirstAccessComponent),
		"BindEventComponentMgrRemoveComponent":        reflect.ValueOf(ec.BindEventComponentMgrRemoveComponent),
		"BindEventEntityDestroySelf":                  reflect.ValueOf(ec.BindEventEntityDestroySelf),
		"BindEventTreeNodeAddChild":                   reflect.ValueOf(ec.BindEventTreeNodeAddChild),
		"BindEventTreeNodeEnterParent":                reflect.ValueOf(ec.BindEventTreeNodeEnterParent),
		"BindEventTreeNodeLeaveParent":                reflect.ValueOf(ec.BindEventTreeNodeLeaveParent),
		"BindEventTreeNodeRemoveChild":                reflect.ValueOf(ec.BindEventTreeNodeRemoveChild),
		"ComponentState_Alive":                        reflect.ValueOf(ec.ComponentState_Alive),
		"ComponentState_Attach":                       reflect.ValueOf(ec.ComponentState_Attach),
		"ComponentState_Awake":                        reflect.ValueOf(ec.ComponentState_Awake),
		"ComponentState_Birth":                        reflect.ValueOf(ec.ComponentState_Birth),
		"ComponentState_Death":                        reflect.ValueOf(ec.ComponentState_Death),
		"ComponentState_Detach":                       reflect.ValueOf(ec.ComponentState_Detach),
		"ComponentState_Shut":                         reflect.ValueOf(ec.ComponentState_Shut),
		"ComponentState_Start":                        reflect.ValueOf(ec.ComponentState_Start),
		"EntityState_Alive":                           reflect.ValueOf(ec.EntityState_Alive),
		"EntityState_Awake":                           reflect.ValueOf(ec.EntityState_Awake),
		"EntityState_Birth":                           reflect.ValueOf(ec.EntityState_Birth),
		"EntityState_Death":                           reflect.ValueOf(ec.EntityState_Death),
		"EntityState_Enter":                           reflect.ValueOf(ec.EntityState_Enter),
		"EntityState_Leave":                           reflect.ValueOf(ec.EntityState_Leave),
		"EntityState_Shut":                            reflect.ValueOf(ec.EntityState_Shut),
		"EntityState_Start":                           reflect.ValueOf(ec.EntityState_Start),
		"ErrEC":                                       reflect.ValueOf(&ec.ErrEC).Elem(),
		"HandleEventComponentDestroySelf":             reflect.ValueOf(ec.HandleEventComponentDestroySelf),
		"HandleEventComponentMgrAddComponents":        reflect.ValueOf(ec.HandleEventComponentMgrAddComponents),
		"HandleEventComponentMgrFirstAccessComponent": reflect.ValueOf(ec.HandleEventComponentMgrFirstAccessComponent),
		"HandleEventComponentMgrRemoveComponent":      reflect.ValueOf(ec.HandleEventComponentMgrRemoveComponent),
		"HandleEventEntityDestroySelf":                reflect.ValueOf(ec.HandleEventEntityDestroySelf),
		"HandleEventTreeNodeAddChild":                 reflect.ValueOf(ec.HandleEventTreeNodeAddChild),
		"HandleEventTreeNodeEnterParent":              reflect.ValueOf(ec.HandleEventTreeNodeEnterParent),
		"HandleEventTreeNodeLeaveParent":              reflect.ValueOf(ec.HandleEventTreeNodeLeaveParent),
		"HandleEventTreeNodeRemoveChild":              reflect.ValueOf(ec.HandleEventTreeNodeRemoveChild),
		"NewEntity":                                   reflect.ValueOf(ec.NewEntity),
		"Scope_Global":                                reflect.ValueOf(ec.Scope_Global),
		"Scope_Local":                                 reflect.ValueOf(ec.Scope_Local),
		"TreeNodeState_Attached":                      reflect.ValueOf(ec.TreeNodeState_Attached),
		"TreeNodeState_Attaching":                     reflect.ValueOf(ec.TreeNodeState_Attaching),
		"TreeNodeState_Detaching":                     reflect.ValueOf(ec.TreeNodeState_Detaching),
		"TreeNodeState_Freedom":                       reflect.ValueOf(ec.TreeNodeState_Freedom),
		"UnsafeComponent":                             reflect.ValueOf(ec.UnsafeComponent),
		"UnsafeConcurrentEntity":                      reflect.ValueOf(ec.UnsafeConcurrentEntity),
		"UnsafeEntity":                                reflect.ValueOf(ec.UnsafeEntity),
		"UnsafeNewEntity":                             reflect.ValueOf(ec.UnsafeNewEntity),
		"With":                                        reflect.ValueOf(&ec.With).Elem(),

		// type definitions
		"Component":                                    reflect.ValueOf((*ec.Component)(nil)),
		"ComponentBehavior":                            reflect.ValueOf((*ec.ComponentBehavior)(nil)),
		"ComponentState":                               reflect.ValueOf((*ec.ComponentState)(nil)),
		"ConcurrentEntity":                             reflect.ValueOf((*ec.ConcurrentEntity)(nil)),
		"Entity":                                       reflect.ValueOf((*ec.Entity)(nil)),
		"EntityBehavior":                               reflect.ValueOf((*ec.EntityBehavior)(nil)),
		"EntityOptions":                                reflect.ValueOf((*ec.EntityOptions)(nil)),
		"EntityState":                                  reflect.ValueOf((*ec.EntityState)(nil)),
		"EventComponentDestroySelf":                    reflect.ValueOf((*ec.EventComponentDestroySelf)(nil)),
		"EventComponentDestroySelfHandler":             reflect.ValueOf((*ec.EventComponentDestroySelfHandler)(nil)),
		"EventComponentMgrAddComponents":               reflect.ValueOf((*ec.EventComponentMgrAddComponents)(nil)),
		"EventComponentMgrAddComponentsHandler":        reflect.ValueOf((*ec.EventComponentMgrAddComponentsHandler)(nil)),
		"EventComponentMgrFirstAccessComponent":        reflect.ValueOf((*ec.EventComponentMgrFirstAccessComponent)(nil)),
		"EventComponentMgrFirstAccessComponentHandler": reflect.ValueOf((*ec.EventComponentMgrFirstAccessComponentHandler)(nil)),
		"EventComponentMgrRemoveComponent":             reflect.ValueOf((*ec.EventComponentMgrRemoveComponent)(nil)),
		"EventComponentMgrRemoveComponentHandler":      reflect.ValueOf((*ec.EventComponentMgrRemoveComponentHandler)(nil)),
		"EventEntityDestroySelf":                       reflect.ValueOf((*ec.EventEntityDestroySelf)(nil)),
		"EventEntityDestroySelfHandler":                reflect.ValueOf((*ec.EventEntityDestroySelfHandler)(nil)),
		"EventTreeNodeAddChild":                        reflect.ValueOf((*ec.EventTreeNodeAddChild)(nil)),
		"EventTreeNodeAddChildHandler":                 reflect.ValueOf((*ec.EventTreeNodeAddChildHandler)(nil)),
		"EventTreeNodeEnterParent":                     reflect.ValueOf((*ec.EventTreeNodeEnterParent)(nil)),
		"EventTreeNodeEnterParentHandler":              reflect.ValueOf((*ec.EventTreeNodeEnterParentHandler)(nil)),
		"EventTreeNodeLeaveParent":                     reflect.ValueOf((*ec.EventTreeNodeLeaveParent)(nil)),
		"EventTreeNodeLeaveParentHandler":              reflect.ValueOf((*ec.EventTreeNodeLeaveParentHandler)(nil)),
		"EventTreeNodeRemoveChild":                     reflect.ValueOf((*ec.EventTreeNodeRemoveChild)(nil)),
		"EventTreeNodeRemoveChildHandler":              reflect.ValueOf((*ec.EventTreeNodeRemoveChildHandler)(nil)),
		"Scope":                                        reflect.ValueOf((*ec.Scope)(nil)),
		"TreeNodeState":                                reflect.ValueOf((*ec.TreeNodeState)(nil)),

		// interface wrapper definitions
		"_Component":                             reflect.ValueOf((*_git_golaxy_org_core_ec_Component)(nil)),
		"_ConcurrentEntity":                      reflect.ValueOf((*_git_golaxy_org_core_ec_ConcurrentEntity)(nil)),
		"_Entity":                                reflect.ValueOf((*_git_golaxy_org_core_ec_Entity)(nil)),
		"_EventComponentDestroySelf":             reflect.ValueOf((*_git_golaxy_org_core_ec_EventComponentDestroySelf)(nil)),
		"_EventComponentMgrAddComponents":        reflect.ValueOf((*_git_golaxy_org_core_ec_EventComponentMgrAddComponents)(nil)),
		"_EventComponentMgrFirstAccessComponent": reflect.ValueOf((*_git_golaxy_org_core_ec_EventComponentMgrFirstAccessComponent)(nil)),
		"_EventComponentMgrRemoveComponent":      reflect.ValueOf((*_git_golaxy_org_core_ec_EventComponentMgrRemoveComponent)(nil)),
		"_EventEntityDestroySelf":                reflect.ValueOf((*_git_golaxy_org_core_ec_EventEntityDestroySelf)(nil)),
		"_EventTreeNodeAddChild":                 reflect.ValueOf((*_git_golaxy_org_core_ec_EventTreeNodeAddChild)(nil)),
		"_EventTreeNodeEnterParent":              reflect.ValueOf((*_git_golaxy_org_core_ec_EventTreeNodeEnterParent)(nil)),
		"_EventTreeNodeLeaveParent":              reflect.ValueOf((*_git_golaxy_org_core_ec_EventTreeNodeLeaveParent)(nil)),
		"_EventTreeNodeRemoveChild":              reflect.ValueOf((*_git_golaxy_org_core_ec_EventTreeNodeRemoveChild)(nil)),
	}
}

// _git_golaxy_org_core_ec_Component is an interface wrapper for Component type
type _git_golaxy_org_core_ec_Component struct {
	IValue                     interface{}
	WDeadline                  func() (deadline time.Time, ok bool)
	WDestroySelf               func()
	WDone                      func() <-chan struct{}
	WErr                       func() error
	WEventComponentDestroySelf func() event.IEvent
	WGetConcurrentContext      func() iface.Cache
	WGetCurrentContext         func() iface.Cache
	WGetEntity                 func() ec.Entity
	WGetId                     func() uid.Id
	WGetName                   func() string
	WGetNonRemovable           func() bool
	WGetReflected              func() reflect.Value
	WGetState                  func() ec.ComponentState
	WString                    func() string
	WTerminated                func() <-chan struct{}
	WValue                     func(key any) any
}

func (W _git_golaxy_org_core_ec_Component) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_ec_Component) DestroySelf() {
	W.WDestroySelf()
}
func (W _git_golaxy_org_core_ec_Component) Done() <-chan struct{} {
	return W.WDone()
}
func (W _git_golaxy_org_core_ec_Component) Err() error {
	return W.WErr()
}
func (W _git_golaxy_org_core_ec_Component) EventComponentDestroySelf() event.IEvent {
	return W.WEventComponentDestroySelf()
}
func (W _git_golaxy_org_core_ec_Component) GetConcurrentContext() iface.Cache {
	return W.WGetConcurrentContext()
}
func (W _git_golaxy_org_core_ec_Component) GetCurrentContext() iface.Cache {
	return W.WGetCurrentContext()
}
func (W _git_golaxy_org_core_ec_Component) GetEntity() ec.Entity {
	return W.WGetEntity()
}
func (W _git_golaxy_org_core_ec_Component) GetId() uid.Id {
	return W.WGetId()
}
func (W _git_golaxy_org_core_ec_Component) GetName() string {
	return W.WGetName()
}
func (W _git_golaxy_org_core_ec_Component) GetNonRemovable() bool {
	return W.WGetNonRemovable()
}
func (W _git_golaxy_org_core_ec_Component) GetReflected() reflect.Value {
	return W.WGetReflected()
}
func (W _git_golaxy_org_core_ec_Component) GetState() ec.ComponentState {
	return W.WGetState()
}
func (W _git_golaxy_org_core_ec_Component) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_ec_Component) Terminated() <-chan struct{} {
	return W.WTerminated()
}
func (W _git_golaxy_org_core_ec_Component) Value(key any) any {
	return W.WValue(key)
}

// _git_golaxy_org_core_ec_ConcurrentEntity is an interface wrapper for ConcurrentEntity type
type _git_golaxy_org_core_ec_ConcurrentEntity struct {
	IValue                interface{}
	WDeadline             func() (deadline time.Time, ok bool)
	WDone                 func() <-chan struct{}
	WErr                  func() error
	WGetConcurrentContext func() iface.Cache
	WGetId                func() uid.Id
	WGetPrototype         func() string
	WString               func() string
	WTerminated           func() <-chan struct{}
	WValue                func(key any) any
}

func (W _git_golaxy_org_core_ec_ConcurrentEntity) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) Done() <-chan struct{} {
	return W.WDone()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) Err() error {
	return W.WErr()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) GetConcurrentContext() iface.Cache {
	return W.WGetConcurrentContext()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) GetId() uid.Id {
	return W.WGetId()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) GetPrototype() string {
	return W.WGetPrototype()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) Terminated() <-chan struct{} {
	return W.WTerminated()
}
func (W _git_golaxy_org_core_ec_ConcurrentEntity) Value(key any) any {
	return W.WValue(key)
}

// _git_golaxy_org_core_ec_Entity is an interface wrapper for Entity type
type _git_golaxy_org_core_ec_Entity struct {
	IValue                                 interface{}
	WAddComponent                          func(name string, components ...ec.Component) error
	WContainsComponent                     func(name string) bool
	WContainsComponentById                 func(id uid.Id) bool
	WCountComponents                       func() int
	WDeadline                              func() (deadline time.Time, ok bool)
	WDestroySelf                           func()
	WDone                                  func() <-chan struct{}
	WErr                                   func() error
	WEventComponentMgrAddComponents        func() event.IEvent
	WEventComponentMgrFirstAccessComponent func() event.IEvent
	WEventComponentMgrRemoveComponent      func() event.IEvent
	WEventEntityDestroySelf                func() event.IEvent
	WEventTreeNodeAddChild                 func() event.IEvent
	WEventTreeNodeEnterParent              func() event.IEvent
	WEventTreeNodeLeaveParent              func() event.IEvent
	WEventTreeNodeRemoveChild              func() event.IEvent
	WFilterComponents                      func(fun generic.Func1[ec.Component, bool]) []ec.Component
	WGetComponent                          func(name string) ec.Component
	WGetComponentById                      func(id uid.Id) ec.Component
	WGetComponents                         func() []ec.Component
	WGetConcurrentContext                  func() iface.Cache
	WGetCurrentContext                     func() iface.Cache
	WGetId                                 func() uid.Id
	WGetInstanceFaceCache                  func() iface.Cache
	WGetMeta                               func() generic.SliceMap[string, any]
	WGetPrototype                          func() string
	WGetReflected                          func() reflect.Value
	WGetScope                              func() ec.Scope
	WGetState                              func() ec.EntityState
	WGetTreeNodeParent                     func() (ec.Entity, bool)
	WGetTreeNodeState                      func() ec.TreeNodeState
	WRangeComponents                       func(fun generic.Func1[ec.Component, bool])
	WRemoveComponent                       func(name string)
	WRemoveComponentById                   func(id uid.Id)
	WReversedRangeComponents               func(fun generic.Func1[ec.Component, bool])
	WString                                func() string
	WTerminated                            func() <-chan struct{}
	WValue                                 func(key any) any
}

func (W _git_golaxy_org_core_ec_Entity) AddComponent(name string, components ...ec.Component) error {
	return W.WAddComponent(name, components...)
}
func (W _git_golaxy_org_core_ec_Entity) ContainsComponent(name string) bool {
	return W.WContainsComponent(name)
}
func (W _git_golaxy_org_core_ec_Entity) ContainsComponentById(id uid.Id) bool {
	return W.WContainsComponentById(id)
}
func (W _git_golaxy_org_core_ec_Entity) CountComponents() int {
	return W.WCountComponents()
}
func (W _git_golaxy_org_core_ec_Entity) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_ec_Entity) DestroySelf() {
	W.WDestroySelf()
}
func (W _git_golaxy_org_core_ec_Entity) Done() <-chan struct{} {
	return W.WDone()
}
func (W _git_golaxy_org_core_ec_Entity) Err() error {
	return W.WErr()
}
func (W _git_golaxy_org_core_ec_Entity) EventComponentMgrAddComponents() event.IEvent {
	return W.WEventComponentMgrAddComponents()
}
func (W _git_golaxy_org_core_ec_Entity) EventComponentMgrFirstAccessComponent() event.IEvent {
	return W.WEventComponentMgrFirstAccessComponent()
}
func (W _git_golaxy_org_core_ec_Entity) EventComponentMgrRemoveComponent() event.IEvent {
	return W.WEventComponentMgrRemoveComponent()
}
func (W _git_golaxy_org_core_ec_Entity) EventEntityDestroySelf() event.IEvent {
	return W.WEventEntityDestroySelf()
}
func (W _git_golaxy_org_core_ec_Entity) EventTreeNodeAddChild() event.IEvent {
	return W.WEventTreeNodeAddChild()
}
func (W _git_golaxy_org_core_ec_Entity) EventTreeNodeEnterParent() event.IEvent {
	return W.WEventTreeNodeEnterParent()
}
func (W _git_golaxy_org_core_ec_Entity) EventTreeNodeLeaveParent() event.IEvent {
	return W.WEventTreeNodeLeaveParent()
}
func (W _git_golaxy_org_core_ec_Entity) EventTreeNodeRemoveChild() event.IEvent {
	return W.WEventTreeNodeRemoveChild()
}
func (W _git_golaxy_org_core_ec_Entity) FilterComponents(fun generic.Func1[ec.Component, bool]) []ec.Component {
	return W.WFilterComponents(fun)
}
func (W _git_golaxy_org_core_ec_Entity) GetComponent(name string) ec.Component {
	return W.WGetComponent(name)
}
func (W _git_golaxy_org_core_ec_Entity) GetComponentById(id uid.Id) ec.Component {
	return W.WGetComponentById(id)
}
func (W _git_golaxy_org_core_ec_Entity) GetComponents() []ec.Component {
	return W.WGetComponents()
}
func (W _git_golaxy_org_core_ec_Entity) GetConcurrentContext() iface.Cache {
	return W.WGetConcurrentContext()
}
func (W _git_golaxy_org_core_ec_Entity) GetCurrentContext() iface.Cache {
	return W.WGetCurrentContext()
}
func (W _git_golaxy_org_core_ec_Entity) GetId() uid.Id {
	return W.WGetId()
}
func (W _git_golaxy_org_core_ec_Entity) GetInstanceFaceCache() iface.Cache {
	return W.WGetInstanceFaceCache()
}
func (W _git_golaxy_org_core_ec_Entity) GetMeta() generic.SliceMap[string, any] {
	return W.WGetMeta()
}
func (W _git_golaxy_org_core_ec_Entity) GetPrototype() string {
	return W.WGetPrototype()
}
func (W _git_golaxy_org_core_ec_Entity) GetReflected() reflect.Value {
	return W.WGetReflected()
}
func (W _git_golaxy_org_core_ec_Entity) GetScope() ec.Scope {
	return W.WGetScope()
}
func (W _git_golaxy_org_core_ec_Entity) GetState() ec.EntityState {
	return W.WGetState()
}
func (W _git_golaxy_org_core_ec_Entity) GetTreeNodeParent() (ec.Entity, bool) {
	return W.WGetTreeNodeParent()
}
func (W _git_golaxy_org_core_ec_Entity) GetTreeNodeState() ec.TreeNodeState {
	return W.WGetTreeNodeState()
}
func (W _git_golaxy_org_core_ec_Entity) RangeComponents(fun generic.Func1[ec.Component, bool]) {
	W.WRangeComponents(fun)
}
func (W _git_golaxy_org_core_ec_Entity) RemoveComponent(name string) {
	W.WRemoveComponent(name)
}
func (W _git_golaxy_org_core_ec_Entity) RemoveComponentById(id uid.Id) {
	W.WRemoveComponentById(id)
}
func (W _git_golaxy_org_core_ec_Entity) ReversedRangeComponents(fun generic.Func1[ec.Component, bool]) {
	W.WReversedRangeComponents(fun)
}
func (W _git_golaxy_org_core_ec_Entity) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_ec_Entity) Terminated() <-chan struct{} {
	return W.WTerminated()
}
func (W _git_golaxy_org_core_ec_Entity) Value(key any) any {
	return W.WValue(key)
}

// _git_golaxy_org_core_ec_EventComponentDestroySelf is an interface wrapper for EventComponentDestroySelf type
type _git_golaxy_org_core_ec_EventComponentDestroySelf struct {
	IValue                  interface{}
	WOnComponentDestroySelf func(comp ec.Component)
}

func (W _git_golaxy_org_core_ec_EventComponentDestroySelf) OnComponentDestroySelf(comp ec.Component) {
	W.WOnComponentDestroySelf(comp)
}

// _git_golaxy_org_core_ec_EventComponentMgrAddComponents is an interface wrapper for EventComponentMgrAddComponents type
type _git_golaxy_org_core_ec_EventComponentMgrAddComponents struct {
	IValue                       interface{}
	WOnComponentMgrAddComponents func(entity ec.Entity, components []ec.Component)
}

func (W _git_golaxy_org_core_ec_EventComponentMgrAddComponents) OnComponentMgrAddComponents(entity ec.Entity, components []ec.Component) {
	W.WOnComponentMgrAddComponents(entity, components)
}

// _git_golaxy_org_core_ec_EventComponentMgrFirstAccessComponent is an interface wrapper for EventComponentMgrFirstAccessComponent type
type _git_golaxy_org_core_ec_EventComponentMgrFirstAccessComponent struct {
	IValue                              interface{}
	WOnComponentMgrFirstAccessComponent func(entity ec.Entity, component ec.Component)
}

func (W _git_golaxy_org_core_ec_EventComponentMgrFirstAccessComponent) OnComponentMgrFirstAccessComponent(entity ec.Entity, component ec.Component) {
	W.WOnComponentMgrFirstAccessComponent(entity, component)
}

// _git_golaxy_org_core_ec_EventComponentMgrRemoveComponent is an interface wrapper for EventComponentMgrRemoveComponent type
type _git_golaxy_org_core_ec_EventComponentMgrRemoveComponent struct {
	IValue                         interface{}
	WOnComponentMgrRemoveComponent func(entity ec.Entity, component ec.Component)
}

func (W _git_golaxy_org_core_ec_EventComponentMgrRemoveComponent) OnComponentMgrRemoveComponent(entity ec.Entity, component ec.Component) {
	W.WOnComponentMgrRemoveComponent(entity, component)
}

// _git_golaxy_org_core_ec_EventEntityDestroySelf is an interface wrapper for EventEntityDestroySelf type
type _git_golaxy_org_core_ec_EventEntityDestroySelf struct {
	IValue               interface{}
	WOnEntityDestroySelf func(entity ec.Entity)
}

func (W _git_golaxy_org_core_ec_EventEntityDestroySelf) OnEntityDestroySelf(entity ec.Entity) {
	W.WOnEntityDestroySelf(entity)
}

// _git_golaxy_org_core_ec_EventTreeNodeAddChild is an interface wrapper for EventTreeNodeAddChild type
type _git_golaxy_org_core_ec_EventTreeNodeAddChild struct {
	IValue              interface{}
	WOnTreeNodeAddChild func(self ec.Entity, child ec.Entity)
}

func (W _git_golaxy_org_core_ec_EventTreeNodeAddChild) OnTreeNodeAddChild(self ec.Entity, child ec.Entity) {
	W.WOnTreeNodeAddChild(self, child)
}

// _git_golaxy_org_core_ec_EventTreeNodeEnterParent is an interface wrapper for EventTreeNodeEnterParent type
type _git_golaxy_org_core_ec_EventTreeNodeEnterParent struct {
	IValue                 interface{}
	WOnTreeNodeEnterParent func(self ec.Entity, parent ec.Entity)
}

func (W _git_golaxy_org_core_ec_EventTreeNodeEnterParent) OnTreeNodeEnterParent(self ec.Entity, parent ec.Entity) {
	W.WOnTreeNodeEnterParent(self, parent)
}

// _git_golaxy_org_core_ec_EventTreeNodeLeaveParent is an interface wrapper for EventTreeNodeLeaveParent type
type _git_golaxy_org_core_ec_EventTreeNodeLeaveParent struct {
	IValue                 interface{}
	WOnTreeNodeLeaveParent func(self ec.Entity, parent ec.Entity)
}

func (W _git_golaxy_org_core_ec_EventTreeNodeLeaveParent) OnTreeNodeLeaveParent(self ec.Entity, parent ec.Entity) {
	W.WOnTreeNodeLeaveParent(self, parent)
}

// _git_golaxy_org_core_ec_EventTreeNodeRemoveChild is an interface wrapper for EventTreeNodeRemoveChild type
type _git_golaxy_org_core_ec_EventTreeNodeRemoveChild struct {
	IValue                 interface{}
	WOnTreeNodeRemoveChild func(self ec.Entity, child ec.Entity)
}

func (W _git_golaxy_org_core_ec_EventTreeNodeRemoveChild) OnTreeNodeRemoveChild(self ec.Entity, child ec.Entity) {
	W.WOnTreeNodeRemoveChild(self, child)
}
