// Code generated by 'yaegi extract git.golaxy.org/framework/net/netpath'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/net/netpath"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/net/netpath/netpath"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Base":  reflect.ValueOf(netpath.Base),
		"Dir":   reflect.ValueOf(netpath.Dir),
		"Equal": reflect.ValueOf(netpath.Equal),
		"InDir": reflect.ValueOf(netpath.InDir),
		"Join":  reflect.ValueOf(netpath.Join),
		"Root":  reflect.ValueOf(netpath.Root),
		"Split": reflect.ValueOf(netpath.Split),

		// type definitions
		"Domain":      reflect.ValueOf((*netpath.Domain)(nil)),
		"NodeDetails": reflect.ValueOf((*netpath.NodeDetails)(nil)),
	}
}
