// Code generated by 'yaegi extract git.golaxy.org/framework/utils/concurrent'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/framework/utils/concurrent"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/utils/concurrent/concurrent"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CacheDefaultCleanInterval":  reflect.ValueOf(concurrent.CacheDefaultCleanInterval),
		"CacheDefaultCleanNum":       reflect.ValueOf(constant.MakeFromLiteral("64", token.INT, 0)),
		"ErrFutureCanceled":          reflect.ValueOf(&concurrent.ErrFutureCanceled).Elem(),
		"ErrFutureNotFound":          reflect.ValueOf(&concurrent.ErrFutureNotFound).Elem(),
		"ErrFutureRespIncorrectType": reflect.ValueOf(&concurrent.ErrFutureRespIncorrectType).Elem(),
		"ErrFutureTimeout":           reflect.ValueOf(&concurrent.ErrFutureTimeout).Elem(),
		"ErrFuturesClosed":           reflect.ValueOf(&concurrent.ErrFuturesClosed).Elem(),
		"MakeFutureRespAsyncRet":     reflect.ValueOf(concurrent.MakeFutureRespAsyncRet),
		"MakeRespAsyncRet":           reflect.ValueOf(concurrent.MakeRespAsyncRet),
		"NewDeduplicator":            reflect.ValueOf(concurrent.NewDeduplicator),
		"NewFutures":                 reflect.ValueOf(concurrent.NewFutures),

		// type definitions
		"Deduplicator": reflect.ValueOf((*concurrent.Deduplicator)(nil)),
		"Future":       reflect.ValueOf((*concurrent.Future)(nil)),
		"Futures":      reflect.ValueOf((*concurrent.Futures)(nil)),
		"Resp":         reflect.ValueOf((*concurrent.Resp)(nil)),
		"RespAsyncRet": reflect.ValueOf((*concurrent.RespAsyncRet)(nil)),

		// interface wrapper definitions
		"_Resp": reflect.ValueOf((*_git_golaxy_org_framework_utils_concurrent_Resp)(nil)),
	}
}

// _git_golaxy_org_framework_utils_concurrent_Resp is an interface wrapper for Resp type
type _git_golaxy_org_framework_utils_concurrent_Resp struct {
	IValue interface{}
	WPush  func(ret async.RetT[any]) error
}

func (W _git_golaxy_org_framework_utils_concurrent_Resp) Push(ret async.RetT[any]) error {
	return W.WPush(ret)
}
