// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/log/console_log'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/plugins/log/console_log"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/log/console_log/console_log"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Install":   reflect.ValueOf(&console_log.Install).Elem(),
		"Uninstall": reflect.ValueOf(&console_log.Uninstall).Elem(),
		"With":      reflect.ValueOf(&console_log.With).Elem(),

		// type definitions
		"LoggerOptions": reflect.ValueOf((*console_log.LoggerOptions)(nil)),
	}
}
