// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/dentr'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/event"
	"git.golaxy.org/framework/plugins/dentr"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/dentr/dentr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindEventDistEntityOffline":   reflect.ValueOf(dentr.BindEventDistEntityOffline),
		"BindEventDistEntityOnline":    reflect.ValueOf(dentr.BindEventDistEntityOnline),
		"EventDistEntityOfflineId":     reflect.ValueOf(&dentr.EventDistEntityOfflineId).Elem(),
		"EventDistEntityOnlineId":      reflect.ValueOf(&dentr.EventDistEntityOnlineId).Elem(),
		"HandleEventDistEntityOffline": reflect.ValueOf(dentr.HandleEventDistEntityOffline),
		"HandleEventDistEntityOnline":  reflect.ValueOf(dentr.HandleEventDistEntityOnline),
		"Install":                      reflect.ValueOf(&dentr.Install).Elem(),
		"Name":                         reflect.ValueOf(&dentr.Name).Elem(),
		"Uninstall":                    reflect.ValueOf(&dentr.Uninstall).Elem(),
		"Using":                        reflect.ValueOf(&dentr.Using).Elem(),
		"With":                         reflect.ValueOf(&dentr.With).Elem(),

		// type definitions
		"DistEntityRegistryOptions":     reflect.ValueOf((*dentr.DistEntityRegistryOptions)(nil)),
		"EventDistEntityOffline":        reflect.ValueOf((*dentr.EventDistEntityOffline)(nil)),
		"EventDistEntityOfflineHandler": reflect.ValueOf((*dentr.EventDistEntityOfflineHandler)(nil)),
		"EventDistEntityOnline":         reflect.ValueOf((*dentr.EventDistEntityOnline)(nil)),
		"EventDistEntityOnlineHandler":  reflect.ValueOf((*dentr.EventDistEntityOnlineHandler)(nil)),
		"IDistEntityRegistry":           reflect.ValueOf((*dentr.IDistEntityRegistry)(nil)),
		"IDistEntityRegistryEventTab":   reflect.ValueOf((*dentr.IDistEntityRegistryEventTab)(nil)),

		// interface wrapper definitions
		"_EventDistEntityOffline":      reflect.ValueOf((*_git_golaxy_org_framework_plugins_dentr_EventDistEntityOffline)(nil)),
		"_EventDistEntityOnline":       reflect.ValueOf((*_git_golaxy_org_framework_plugins_dentr_EventDistEntityOnline)(nil)),
		"_IDistEntityRegistry":         reflect.ValueOf((*_git_golaxy_org_framework_plugins_dentr_IDistEntityRegistry)(nil)),
		"_IDistEntityRegistryEventTab": reflect.ValueOf((*_git_golaxy_org_framework_plugins_dentr_IDistEntityRegistryEventTab)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_dentr_EventDistEntityOffline is an interface wrapper for EventDistEntityOffline type
type _git_golaxy_org_framework_plugins_dentr_EventDistEntityOffline struct {
	IValue               interface{}
	WOnDistEntityOffline func(entity ec.Entity)
}

func (W _git_golaxy_org_framework_plugins_dentr_EventDistEntityOffline) OnDistEntityOffline(entity ec.Entity) {
	W.WOnDistEntityOffline(entity)
}

// _git_golaxy_org_framework_plugins_dentr_EventDistEntityOnline is an interface wrapper for EventDistEntityOnline type
type _git_golaxy_org_framework_plugins_dentr_EventDistEntityOnline struct {
	IValue              interface{}
	WOnDistEntityOnline func(entity ec.Entity)
}

func (W _git_golaxy_org_framework_plugins_dentr_EventDistEntityOnline) OnDistEntityOnline(entity ec.Entity) {
	W.WOnDistEntityOnline(entity)
}

// _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistry is an interface wrapper for IDistEntityRegistry type
type _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistry struct {
	IValue                  interface{}
	WEventDistEntityOffline func() event.IEvent
	WEventDistEntityOnline  func() event.IEvent
}

func (W _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistry) EventDistEntityOffline() event.IEvent {
	return W.WEventDistEntityOffline()
}
func (W _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistry) EventDistEntityOnline() event.IEvent {
	return W.WEventDistEntityOnline()
}

// _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistryEventTab is an interface wrapper for IDistEntityRegistryEventTab type
type _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistryEventTab struct {
	IValue                  interface{}
	WEventDistEntityOffline func() event.IEvent
	WEventDistEntityOnline  func() event.IEvent
}

func (W _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistryEventTab) EventDistEntityOffline() event.IEvent {
	return W.WEventDistEntityOffline()
}
func (W _git_golaxy_org_framework_plugins_dentr_IDistEntityRegistryEventTab) EventDistEntityOnline() event.IEvent {
	return W.WEventDistEntityOnline()
}
