// Code generated by 'yaegi extract git.golaxy.org/framework/plugins/rpc/rpcpcsr'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/service"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/framework/net/gap/variant"
	"git.golaxy.org/framework/plugins/rpc/callpath"
	"git.golaxy.org/framework/plugins/rpc/rpcpcsr"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/plugins/rpc/rpcpcsr/rpcpcsr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CallEntity":                      reflect.ValueOf(rpcpcsr.CallEntity),
		"CallRuntime":                     reflect.ValueOf(rpcpcsr.CallRuntime),
		"CallService":                     reflect.ValueOf(rpcpcsr.CallService),
		"ErrComponentNotFound":            reflect.ValueOf(&rpcpcsr.ErrComponentNotFound).Elem(),
		"ErrDistEntityNodeNotFound":       reflect.ValueOf(&rpcpcsr.ErrDistEntityNodeNotFound).Elem(),
		"ErrDistEntityNotFound":           reflect.ValueOf(&rpcpcsr.ErrDistEntityNotFound).Elem(),
		"ErrEntityNotFound":               reflect.ValueOf(&rpcpcsr.ErrEntityNotFound).Elem(),
		"ErrGroupChanIsFull":              reflect.ValueOf(&rpcpcsr.ErrGroupChanIsFull).Elem(),
		"ErrGroupNotFound":                reflect.ValueOf(&rpcpcsr.ErrGroupNotFound).Elem(),
		"ErrIncorrectDestAddress":         reflect.ValueOf(&rpcpcsr.ErrIncorrectDestAddress).Elem(),
		"ErrMethodNotFound":               reflect.ValueOf(&rpcpcsr.ErrMethodNotFound).Elem(),
		"ErrMethodParameterCountMismatch": reflect.ValueOf(&rpcpcsr.ErrMethodParameterCountMismatch).Elem(),
		"ErrMethodParameterTypeMismatch":  reflect.ValueOf(&rpcpcsr.ErrMethodParameterTypeMismatch).Elem(),
		"ErrPermissionDenied":             reflect.ValueOf(&rpcpcsr.ErrPermissionDenied).Elem(),
		"ErrPluginInactive":               reflect.ValueOf(&rpcpcsr.ErrPluginInactive).Elem(),
		"ErrPluginNotFound":               reflect.ValueOf(&rpcpcsr.ErrPluginNotFound).Elem(),
		"ErrSessionNotFound":              reflect.ValueOf(&rpcpcsr.ErrSessionNotFound).Elem(),
		"ErrTerminated":                   reflect.ValueOf(&rpcpcsr.ErrTerminated).Elem(),
		"ErrUndeliverable":                reflect.ValueOf(&rpcpcsr.ErrUndeliverable).Elem(),
		"NewForwardProcessor":             reflect.ValueOf(rpcpcsr.NewForwardProcessor),
		"NewGateProcessor":                reflect.ValueOf(rpcpcsr.NewGateProcessor),
		"NewServiceProcessor":             reflect.ValueOf(rpcpcsr.NewServiceProcessor),

		// type definitions
		"IDeliverer":    reflect.ValueOf((*rpcpcsr.IDeliverer)(nil)),
		"LifecycleInit": reflect.ValueOf((*rpcpcsr.LifecycleInit)(nil)),
		"LifecycleShut": reflect.ValueOf((*rpcpcsr.LifecycleShut)(nil)),

		// interface wrapper definitions
		"_IDeliverer":    reflect.ValueOf((*_git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer)(nil)),
		"_LifecycleInit": reflect.ValueOf((*_git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleInit)(nil)),
		"_LifecycleShut": reflect.ValueOf((*_git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleShut)(nil)),
	}
}

// _git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer is an interface wrapper for IDeliverer type
type _git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer struct {
	IValue   interface{}
	WMatch   func(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, oneway bool) bool
	WNotify  func(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, args []any) error
	WRequest func(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, args []any) async.AsyncRetT[any]
}

func (W _git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer) Match(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, oneway bool) bool {
	return W.WMatch(svcCtx, dst, cc, cp, oneway)
}
func (W _git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer) Notify(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, args []any) error {
	return W.WNotify(svcCtx, dst, cc, cp, args)
}
func (W _git_golaxy_org_framework_plugins_rpc_rpcpcsr_IDeliverer) Request(svcCtx service.Context, dst string, cc variant.CallChain, cp callpath.CallPath, args []any) async.AsyncRetT[any] {
	return W.WRequest(svcCtx, dst, cc, cp, args)
}

// _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleInit is an interface wrapper for LifecycleInit type
type _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleInit struct {
	IValue interface{}
	WInit  func(svcCtx service.Context)
}

func (W _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleInit) Init(svcCtx service.Context) {
	W.WInit(svcCtx)
}

// _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleShut is an interface wrapper for LifecycleShut type
type _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleShut struct {
	IValue interface{}
	WShut  func(svcCtx service.Context)
}

func (W _git_golaxy_org_framework_plugins_rpc_rpcpcsr_LifecycleShut) Shut(svcCtx service.Context) {
	W.WShut(svcCtx)
}
