// Code generated by 'yaegi extract git.golaxy.org/framework/net/gap/codec'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/net/gap/codec"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/net/gap/codec/codec"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultDecoder": reflect.ValueOf(codec.DefaultDecoder),
		"DefaultEncoder": reflect.ValueOf(codec.DefaultEncoder),
		"ErrDecode":      reflect.ValueOf(&codec.ErrDecode).Elem(),
		"ErrEncode":      reflect.ValueOf(&codec.ErrEncode).Elem(),
		"MakeDecoder":    reflect.ValueOf(codec.MakeDecoder),
		"MakeEncoder":    reflect.ValueOf(codec.MakeEncoder),

		// type definitions
		"Decoder": reflect.ValueOf((*codec.Decoder)(nil)),
		"Encoder": reflect.ValueOf((*codec.Encoder)(nil)),
	}
}
