/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event --default_export=false; DO NOT EDIT.

package dentr

import (
	event "git.golaxy.org/core/event"
	"git.golaxy.org/core/ec"
)

type iAutoEventDistEntityOnline interface {
	EventDistEntityOnline() event.IEvent
}

func BindEventDistEntityOnline(auto iAutoEventDistEntityOnline, subscriber EventDistEntityOnline, priority ...int32) event.Hook {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventDistEntityOnline](auto.EventDistEntityOnline(), subscriber, priority...)
}

func _EmitEventDistEntityOnline(auto iAutoEventDistEntityOnline, entity ec.Entity) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventDistEntityOnline()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventDistEntityOnline](subscriber).OnDistEntityOnline(entity)
		return true
	})
}

func _EmitEventDistEntityOnlineWithInterrupt(auto iAutoEventDistEntityOnline, interrupt func(entity ec.Entity) bool, entity ec.Entity) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventDistEntityOnline()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity) {
				return false
			}
		}
		event.Cache2Iface[EventDistEntityOnline](subscriber).OnDistEntityOnline(entity)
		return true
	})
}

func HandleEventDistEntityOnline(fun func(entity ec.Entity)) EventDistEntityOnlineHandler {
	return EventDistEntityOnlineHandler(fun)
}

type EventDistEntityOnlineHandler func(entity ec.Entity)

func (h EventDistEntityOnlineHandler) OnDistEntityOnline(entity ec.Entity) {
	h(entity)
}

type iAutoEventDistEntityOffline interface {
	EventDistEntityOffline() event.IEvent
}

func BindEventDistEntityOffline(auto iAutoEventDistEntityOffline, subscriber EventDistEntityOffline, priority ...int32) event.Hook {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventDistEntityOffline](auto.EventDistEntityOffline(), subscriber, priority...)
}

func _EmitEventDistEntityOffline(auto iAutoEventDistEntityOffline, entity ec.Entity) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventDistEntityOffline()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventDistEntityOffline](subscriber).OnDistEntityOffline(entity)
		return true
	})
}

func _EmitEventDistEntityOfflineWithInterrupt(auto iAutoEventDistEntityOffline, interrupt func(entity ec.Entity) bool, entity ec.Entity) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventDistEntityOffline()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity) {
				return false
			}
		}
		event.Cache2Iface[EventDistEntityOffline](subscriber).OnDistEntityOffline(entity)
		return true
	})
}

func HandleEventDistEntityOffline(fun func(entity ec.Entity)) EventDistEntityOfflineHandler {
	return EventDistEntityOfflineHandler(fun)
}

type EventDistEntityOfflineHandler func(entity ec.Entity)

func (h EventDistEntityOfflineHandler) OnDistEntityOffline(entity ec.Entity) {
	h(entity)
}
