/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=distEntityRegistryEventTab; DO NOT EDIT.

package dent

import (
	event "git.golaxy.org/core/event"
)

type IDistEntityRegistryEventTab interface {
	EventDistEntityOnline() event.IEvent
	EventDistEntityOffline() event.IEvent
}

var (
	_distEntityRegistryEventTabId = event.DeclareEventTabIdT[distEntityRegistryEventTab]()
	EventDistEntityOnlineId = event.DeclareEventIdT[distEntityRegistryEventTab](0)
	EventDistEntityOfflineId = event.DeclareEventIdT[distEntityRegistryEventTab](1)
)

type distEntityRegistryEventTab [2]event.Event

func (eventTab *distEntityRegistryEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range eventTab {
		eventTab[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *distEntityRegistryEventTab) SetRecursion(recursion event.EventRecursion) {
	eventTab[0].SetRecursion(event.EventRecursion_Allow)
	eventTab[1].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *distEntityRegistryEventTab) SetEnabled(b bool) {
	for i := range eventTab {
		eventTab[i].SetEnabled(b)
	}
}

func (eventTab *distEntityRegistryEventTab) UnbindAll() {
	for i := range eventTab {
		eventTab[i].UnbindAll()
	}
}

func (eventTab *distEntityRegistryEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *distEntityRegistryEventTab) Event(id uint64) event.IEvent {
	eventTabId, pos := event.SplitEventId(id)
	if _distEntityRegistryEventTabId != eventTabId || pos >= len(eventTab) {
		return nil
	}
	switch pos {
	case 0:
		eventTab[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		eventTab[1].SetRecursion(event.EventRecursion_Allow)
	}
	return &eventTab[pos]
}

func (eventTab *distEntityRegistryEventTab) EventDistEntityOnline() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[0]
}

func (eventTab *distEntityRegistryEventTab) EventDistEntityOffline() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[1]
}
